version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew --version

  build:
    commands:
      - ./gradlew clean build

artifacts:
  files:
    - build/libs/*.jar
